# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
sudo: required
dist: trusty

os:
  - linux
  - osx

julia:
  - release
  # - nightly

notifications:
  email: false

before_install:
  - travis/setup_lcm.sh
  - echo $PYTHONPATH
  - export PYTHONPATH=$PYTHONPATH:/usr/local/lib/python2.7/site-packages:`julia -e "println(Pkg.dir(\"PyLCM\"))"`

after_success:
  - julia -e 'cd(Pkg.dir("PyLCM")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'

# uncomment the following lines to override the default test script
#script:
#  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#  - julia -e 'Pkg.clone(pwd()); Pkg.build("PyLCM"); Pkg.test("PyLCM"; coverage=true)'
